name: Build and run Dockerfile for bmoran

on:
    push:
        branches:
          - master
        path:
          - 'individual-work/bmoran/**'
          - '.github/workflows/bmoran-workflow.yaml'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest 
          
        steps:
        
          - name: Fetch repository and checkout this branches
            uses: actions/checkout@v2
        
          - name: Login to Docker Hub
            uses: echo ${{ secrets.EKNIGHT_DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.EKNIGHT_DOCKERHUB_USERNAME }} --password-stdin

        
          - name: Build and run docker image
            working-directory: individual-work/bmoran
            run: docker build -t react-demo-$(date +%s) .      
            