name: Build and run Dockerfile for dakinbode

on:
    pull_request:
        branches:
          - master
        path:
          - 'individual-work/dakinbode/**'
          - '.github/workflows/dakinbode-workflow.yaml'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest 
          
        steps:
        
          - name: Fetch repository and checkout this branches
            uses: actions/checkout@v2
        
          - name: Build and run docker image
            working-directory: individual-work/dakinbode
            run: docker build -t test . 

          - name: Run Docker Image  
            working-directory: individual-work/dakinbode
            run: docker run test
            