name: build and run Dockerfile for rgrace
on:
    pull_request:
        branches:
            - master

        paths:
            - '/individual-work/vcradler/**'
            - '.github/workflows/rgrace-workflow.yaml'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Fetch repository and checkout this branch
        uses: actions/checkout@v2

      - name: Please fail, code!
        run: exit

      - name: Building Docker image
        working-directory: ./individual-work/rgrace/
        run: |
            docker build -t test .
      - name: Run Docker image
        working-directory: ./individual-work/rgrace/
        run: docker run test

        
