name: This the the Prebuild file 
on:
    pull_request:
        branches:
            - master

        paths:
            - '/individual-work/vcradler/Dockerfile'
            - '.github/workflows/vcradler-premerge.yml'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Fetch my code repositoy
        uses: actions/checkout@v2

      - name: Please fail, code!
        run: exit

      - name: Building Docker image
        working-directory: ./individual-work/vcradler/
        run: |
            docker build -t vcradler --file Dockerfile
      - name: Run Docker image
        working-directory: ./individual-work/vcradler/
        run: docker run -it -p 3000:3000 vcradler
